#Requires -Version 5.1
# Register a hidden logon task that starts this WSL distro and media2text.
# Run from WSL as the Windows user (no sudo, no Administrator):
#   powershell.exe -NoProfile -ExecutionPolicy Bypass -File scripts/windows/register-wsl-autostart.ps1
param(
    [string]$Distro = "Ubuntu-24.04",
    [string]$LinuxScript = "/home/kino/git/media2text/scripts/wsl-autostart.sh",
    [string]$TaskName = "media2text-wsl-autostart"
)

$ErrorActionPreference = "Stop"

$wslExe = Join-Path $env:SystemRoot "System32\wsl.exe"
$wscriptExe = Join-Path $env:SystemRoot "System32\wscript.exe"
if (-not (Test-Path $wslExe)) {
    throw "wsl.exe not found at $wslExe"
}

$installDir = Join-Path $env:LOCALAPPDATA "media2text"
New-Item -ItemType Directory -Path $installDir -Force | Out-Null
$vbsPath = Join-Path $installDir "wsl-autostart.vbs"

$vbs = @"
' Generated by media2text scripts/windows/register-wsl-autostart.ps1
Option Explicit
Dim sh, cmd
Set sh = CreateObject("WScript.Shell")
cmd = "$wslExe -d $Distro -u root --shell-type login --exec $LinuxScript"
sh.Run cmd, 0, True
"@
$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($vbsPath, $vbs, $utf8)

$action = New-ScheduledTaskAction -Execute $wscriptExe -Argument "`"$vbsPath`""
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$trigger.Delay = "PT30S"
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero)
$settings.Hidden = $true
$principal = New-ScheduledTaskPrincipal `
    -UserId $env:USERNAME `
    -LogonType Interactive `
    -RunLevel Limited

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Force | Out-Null

$startupDir = Join-Path $env:APPDATA "Microsoft\Windows\Start Menu\Programs\Startup"
$legacyBat = Join-Path $startupDir "wsl-Ubuntu-24.04.bat"
if (Test-Path $legacyBat) {
    Remove-Item $legacyBat -Force
}

$wslConfigPath = Join-Path $env:USERPROFILE ".wslconfig"
$wslConfig = ""
if (Test-Path $wslConfigPath) {
    $wslConfig = [System.IO.File]::ReadAllText($wslConfigPath)
    $backupPath = "$wslConfigPath.bak-media2text"
    if (-not (Test-Path $backupPath)) {
        Copy-Item $wslConfigPath $backupPath
    }
}
if ($wslConfig -match '(?m)^\s*instanceIdleTimeout\s*=') {
    $wslConfig = [regex]::Replace($wslConfig, '(?m)^\s*instanceIdleTimeout\s*=.*$', 'instanceIdleTimeout=-1')
} elseif ($wslConfig -notmatch '(?m)^\[general\]') {
    $wslConfig = "[general]`r`ninstanceIdleTimeout=-1`r`n`r`n" + $wslConfig
} else {
    $wslConfig = $wslConfig -replace '(?m)^\[general\]', "[general]`r`ninstanceIdleTimeout=-1"
}
if ($wslConfig -match '(?m)^\s*vmIdleTimeout\s*=') {
    $wslConfig = [regex]::Replace($wslConfig, '(?m)^\s*vmIdleTimeout\s*=.*$', 'vmIdleTimeout=-1')
} elseif ($wslConfig -notmatch '(?m)^\[wsl2\]') {
    $wslConfig = $wslConfig.TrimEnd() + "`r`n`r`n[wsl2]`r`nvmIdleTimeout=-1`r`n"
} else {
    $wslConfig = $wslConfig -replace '(?m)^\[wsl2\]', "[wsl2]`r`nvmIdleTimeout=-1"
}
[System.IO.File]::WriteAllText($wslConfigPath, $wslConfig.TrimEnd() + "`r`n", $utf8)

Write-Host "Registered scheduled task '$TaskName' (At logon, +30s, hidden)."
Write-Host "Launcher: $vbsPath"
Write-Host "WSL idle timeouts set to -1 in $wslConfigPath (takes effect after next wsl --shutdown)."
Write-Host "Removed Startup folder launcher if present: $legacyBat"
